### ISSUE TITLE
Can't open project in Visual Studio 2013

### ISSUE THREAD

**Issue by boergens** [open-ephys-plugins/probe-viewer#2]
I try to open the project and I get the following error message:

![image](https://user-images.githubusercontent.com/1429753/43120746-574b29fe-8ee9-11e8-9925-74aed43e128b.png)
Any advice on how to solve this?

**Comment by jsiegle** [comment]
You'll need to download the [plugin-GUI](https://github.com/open-ephys/plugin-gui) source code into the same directory as the probe-viewer. The probe-viewer project depends on properties (.props) files that are stored there.

You'll need to build the plugin-GUI before compiling the probe-viewer, anyway—the probe-viewer plugin can't be compiled as a standalone application.

**Comment by boergens** [comment]
@jsiegle thanks for your reply! However, that is how I have set it up.
I took a look myself and I think you have many malformed paths in the project definition file, in this specific case the line
https://github.com/open-ephys/probe-viewer/blob/development/ProbeViewer/Builds/VisualStudio2013/ProbeViewer.vcxproj#L82
should just be: 

    <Import Project="..\..\..\Builds\VisualStudio2013\Plugins\Plugin_Debug32.props" />

Anyway, Harbi pointed the precompiled version of ProbeViewer for neuropix out to me, so no hurries

**Comment by jsiegle** [comment]
Weird, I just tested it on another computer and it loaded fine.

What is your directory structure? I have it as:

```
~/GitHub
    /probe-viewer
    /plugin-GUI
```

**Comment by boergens** [comment]
Ah sorry, I misunderstood
"you'll need to download the plugin-GUI source code into the same directory as the probe-viewer"
I literally merged the two folders. In which case, my fix would have made sense. Now it works! Thanks for your help

**Comment by open-ephys** [comment]
Closing as this no longer applies after cmake migration.
